### ISSUE TITLE
Упрощение кода

### ISSUE THREAD

**Issue by PenF00k** [BatmanovSergey/Final_Work#1]
https://github.com/BatmanovSergey/Final_Work/blob/bf9c270bfcd08dc29554f13bca063a9f7a58b3d9/Task/Program.cs#L29

Нельзя тут заменить на `Console.Write(arr[i]);`?

**Comment by BatmanovSergey** [comment]
можно)

**Comment by BatmanovSergey** [comment]
закрыто
